# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
  
- script: |
    git config --global user.email "ness.cero1@gmail.com"
    git config --global user.name "NessDisk"
    git status
  displayName: 'Setup Git and Check Status'
  
- script: |
    git init
    git remote add origin <https://github.com/NessDisk/hotelmadeiro>
    git fetch
    git checkout -b main origin/main
  displayName: 'Initialize Git Repository and Checkout'

 
# - script: |
#     npm install
#   displayName: 'npm install'

# - script: |
#     npm run build
#   displayName: 'npm run build'
